# Generated by Django 5.2 on 2025-05-15 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="expenses",
        ),
        migrations.RemoveField(
            model_name="transactions",
            name="name",
        ),
        migrations.AddField(
            model_name="transactions",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transactions",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="transactions",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactions",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="mode_of_payment",
            field=models.CharField(default="cash", max_length=20),
        ),
        migrations.AddField(
            model_name="transactions",
            name="paid_to",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="type",
            field=models.CharField(
                choices=[("income", "INCOME"), ("expenses", "EXPENSES")],
                default="Income",
                max_length=10,
            ),
        ),
    ]
