# Generated by Django 5.2 on 2025-05-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_expenses_remove_transactions_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
