# Generated by Django 5.1.3 on 2025-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transactions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
