# Generated by Django 5.2.1 on 2025-06-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_transactions_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Ongoing', 'ongoing'), ('Completed', 'completed')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
