# Generated by Django 5.2.1 on 2025-06-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_loans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loans',
            new_name='Loan',
        ),
    ]
