# Generated by Django 5.1.3 on 2025-07-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_loans_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='created_at',
        ),
        migrations.AddField(
            model_name='loan',
            name='emi_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='intrest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='lender',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='loan',
            name='tenure',
            field=models.DecimalField(decimal_places=False, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('CLOSED', 'closed')], max_length=10),
        ),
    ]
