# Generated by Django 5.1.3 on 2025-08-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_loan_amount_remove_loan_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='paid_to',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='source',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('debit', 'DEBIT'), ('credit', 'CREDIT')], default='credit', max_length=10),
        ),
    ]
